### ISSUE TITLE
(tlg0544.tlg001.opp-lat1:3.30) needs different description in its CTS file

### ISSUE THREAD

**Issue by nevenjovanovic** [OpenGreekAndLatin/First1KGreek#2098]
The CTS file description of `tlg0544.tlg001.opp-lat1:3.30` in `First1KGreek/data/tlg0544/tlg001/__cts__.xml` shows that the text is listed as "edition":
```xml
<ti:edition urn="urn:cts:greekLit:tlg0544.tlg001.opp-lat1" workUrn="urn:cts:greekLit:tlg0544.tlg001">
  <ti:label xml:lang="lat">Pyrrhoniae Hypotyposes</ti:label>
  <ti:description xml:lang="lat">Sextus Empiricus, Pyrrhoniae Hypotyposes</ti:description>
</ti:edition>
```
But it is a Latin **translation** of the Greek original. Because of the `edition` tag, I guess, at the moment, in Scaife the text is presented as being in Greek. <https://scaife.perseus.org/library/urn:cts:greekLit:tlg0544.tlg001/> says "Read (Greek)", so the user expects to see two Greek editions. Part of the problem is, of course, in Scaife interface (and I'll report it there too), but the CTS file should also treat Latin version _as a translation_, not as another edition.

**Comment by lcerrato** [comment]
It appears these were changed at the time of the report but the lang attribute should be lat instead of eng. 
https://github.com/OpenGreekAndLatin/First1KGreek/commit/a4dd4c975d9e6ccaa726d118e206289980654a1d#diff-5dd3d3a9e61cf219444f14bb035991fb
https://github.com/OpenGreekAndLatin/First1KGreek/commit/6a8553b42cb373c012e51a3c3de5369c93c1d702#diff-752f7d93611e29bf5f1ca1786af912f7
